platform :android do
  desc "Build and deploy the Android app to Google Play"
  lane :deploy do
    # Google Play로 앱 배포
    supply(
      track: "production", # 배포 트랙: production, beta, internal
      package_name: "com.ipcian.rn", # 앱 패키지 이름
      aab: "./app/build/outputs/bundle/release/app-release.aab" # 빌드된 AAB 파일 경로
    )
  end
end
